
export const LOAD_TASKS = 'LOAD_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'

export const AUTHENTICATED = 'AUTHENTICATED'
export const UnAUTHENTICATED = 'UnAUTHENTICATED'